version: '3.9'

# 開発環境用docker-compose
# フロントエンドはローカルで npm run dev を実行してください

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: jimotoko_db
    environment:
      POSTGRES_DB: jimotoko
      POSTGRES_USER: jimotoko_user
      POSTGRES_PASSWORD: jimotoko_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - jimotoko_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jimotoko_user -d jimotoko"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build: 
      context: ./backend
      platforms:
        - "linux/amd64"
    platform: linux/amd64
    container_name: jimotoko_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://jimotoko_user:jimotoko_password@db:5432/jimotoko
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jimotoko_network

volumes:
  postgres_data:
  media_volume:

networks:
  jimotoko_network:
    driver: bridge